version: '1'

projects:
  - name: TravelTracker
    environments:
      - name: Production
        services:
          - type: web
            name: TripPlanner-BE
            runtime: node
            repo: https://github.com/mykolavorobiov/TripPlanner
            plan: free
            region: oregon
            autoDeployTrigger: off
            buildCommand: npm ci --include=dev && npm run build:api
            startCommand: node dist/apps/api/main.js
            envVars:
              - key: NODE_ENV
                value: production
              - key: SUPABASE_URL
                sync: false
              - key: SUPABASE_PUBLISHABLE_KEY
                sync: false
              - key: FRONTEND_ORIGIN
                sync: false
              - key: COOKIE_SAME_SITE
                value: none

          - type: web
            name: TripPlanner-FE
            runtime: static
            repo: https://github.com/mykolavorobiov/TripPlanner
            buildCommand: npm ci --include=dev && npm run build:front-end:render
            staticPublishPath: ./dist/apps/front-end/browser
            envVars:
              - key: API_URL
                sync: false
            routes:
              - type: redirect
                source: /
                destination: /uk
              - type: rewrite
                source: /en/*
                destination: /en/index.html
              - type: rewrite
                source: /uk/*
                destination: /uk/index.html
              - type: rewrite
                source: /*
                destination: /uk/index.html
            autoDeployTrigger: 'off'
