create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.preserve_created_by()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.created_by = old.created_by;
  return new;
end;
$$;

create table public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  color text,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stops (
  id uuid primary key default gen_random_uuid(),
  "where" text not null,
  datetime timestamptz not null,
  comment text not null default '',
  goal text not null default '',
  map_link text not null default '',
  lat double precision,
  lng double precision,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stop_tags (
  stop_id uuid not null references public.stops(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  primary key (stop_id, tag_id)
);

create table public.hotels (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  "where" text not null,
  image_src text not null default '',
  link text,
  check_in timestamptz not null,
  check_out timestamptz not null,
  comment text,
  map_link text,
  tag_id uuid references public.tags(id) on delete set null,
  stop_id uuid references public.stops(id) on delete set null,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.map_points (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  lat double precision not null,
  lng double precision not null,
  color text,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.routes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  color text not null,
  waypoints jsonb not null default '[]'::jsonb,
  options jsonb not null default '{}'::jsonb,
  info jsonb,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.trip (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index tags_name_idx on public.tags (name);
create index stops_datetime_idx on public.stops (datetime);
create index hotels_check_in_idx on public.hotels (check_in);
create index map_points_created_at_idx on public.map_points (created_at desc);
create index routes_created_at_idx on public.routes (created_at);
create index trip_created_at_idx on public.trip (created_at);

create trigger tags_set_updated_at before update on public.tags
for each row execute function public.set_updated_at();
create trigger tags_preserve_created_by before update on public.tags
for each row execute function public.preserve_created_by();
create trigger stops_set_updated_at before update on public.stops
for each row execute function public.set_updated_at();
create trigger stops_preserve_created_by before update on public.stops
for each row execute function public.preserve_created_by();
create trigger hotels_set_updated_at before update on public.hotels
for each row execute function public.set_updated_at();
create trigger hotels_preserve_created_by before update on public.hotels
for each row execute function public.preserve_created_by();
create trigger map_points_set_updated_at before update on public.map_points
for each row execute function public.set_updated_at();
create trigger map_points_preserve_created_by before update on public.map_points
for each row execute function public.preserve_created_by();
create trigger routes_set_updated_at before update on public.routes
for each row execute function public.set_updated_at();
create trigger routes_preserve_created_by before update on public.routes
for each row execute function public.preserve_created_by();
create trigger trip_set_updated_at before update on public.trip
for each row execute function public.set_updated_at();
create trigger trip_preserve_created_by before update on public.trip
for each row execute function public.preserve_created_by();

alter table public.tags enable row level security;
alter table public.stops enable row level security;
alter table public.stop_tags enable row level security;
alter table public.hotels enable row level security;
alter table public.map_points enable row level security;
alter table public.routes enable row level security;
alter table public.trip enable row level security;

create policy "Authenticated users can read tags" on public.tags for select to authenticated using (true);
create policy "Authenticated users can insert tags" on public.tags for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update tags" on public.tags for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete tags" on public.tags for delete to authenticated using (true);

create policy "Authenticated users can read stops" on public.stops for select to authenticated using (true);
create policy "Authenticated users can insert stops" on public.stops for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update stops" on public.stops for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete stops" on public.stops for delete to authenticated using (true);

create policy "Authenticated users can manage stop tags" on public.stop_tags for all to authenticated using (true) with check (true);

create policy "Authenticated users can read hotels" on public.hotels for select to authenticated using (true);
create policy "Authenticated users can insert hotels" on public.hotels for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update hotels" on public.hotels for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete hotels" on public.hotels for delete to authenticated using (true);

create policy "Authenticated users can read map points" on public.map_points for select to authenticated using (true);
create policy "Authenticated users can insert map points" on public.map_points for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update map points" on public.map_points for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete map points" on public.map_points for delete to authenticated using (true);

create policy "Authenticated users can read routes" on public.routes for select to authenticated using (true);
create policy "Authenticated users can insert routes" on public.routes for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update routes" on public.routes for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete routes" on public.routes for delete to authenticated using (true);

create policy "Authenticated users can read trips" on public.trip for select to authenticated using (true);
create policy "Authenticated users can insert trips" on public.trip for insert to authenticated with check (created_by = auth.uid());
create policy "Authenticated users can update trips" on public.trip for update to authenticated using (true) with check (true);
create policy "Authenticated users can delete trips" on public.trip for delete to authenticated using (true);

alter publication supabase_realtime add table
  public.tags,
  public.stops,
  public.hotels,
  public.map_points,
  public.routes,
  public.trip;
